import "./globals.css";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { inter } from "@/lib/fonts";

export const metadata = {
  title: "Care - Your Personal Health Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" className={`${inter.className} h-full antialiased`}>
        <body className="min-h-full flex flex-col">
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}