import { Geist, Geist_Mono, Manrope, Nunito_Sans } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

export const nunitoSans = Nunito_Sans({
  weight: ['400' ,'500', '600', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: "Care - Your Personal Health Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
