import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-manrope'
})

export const nunitoSans = Nunito_Sans({
  weight: ['400' ,'500', '600', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: "Care - Your Personal Health Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-[60px]">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
